format = """
[░▒▓](#a3aed2)\
[ $os](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$c\
$cmake\
$golang\
$java\
$nodejs\
$php\
$rust\
[](fg:#212736 bg:#313545)\
$time\
[ ](fg:#313545 bg:#1d2230)\
$cmd_duration\
[ ](fg:#1d2230)\
$line_break\
$character"""

[line_break]
disabled = false

[character]
disabled = true
format=''

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
staged = " ${count}"
modified = " ${count}"
renamed = " ${count}"
untracked = "${count}"
deleted = "${count}"
conflicted = "${count}"
stashed = " ${count}"
up_to_date = "󰚰"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "󰯎 ${ahead_count} ${behind_count}"
# ignore_submodules = true
format = '[[$all_status $ahead_behind](fg:#769ff0 bg:#394260)]($style)'

[c]
symbol = ""
style = "bg:#212736"
detect_extensions = ['c', 'cpp', 'cxx', 'cc', 'c++', 'h', 'hpp', 'hh', 'h++']
format = '[[ $symbol ($version()-$name) ](fg:#769ff0 bg:#212736)]($style)'

[cmake]
symbol = '△'
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[java]
symbol = ""
style = "bg:#212736"
format = '[[ ${symbol} (${version}) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#313545"
format = '[[  $time ](fg:#a0a9cb bg:#313545)]($style)'

[cmd_duration]
style = "bg:#1d2230"
format = '[[took $duration ](fg:#a0a9cb bg:#1d2230)]($style)'


[os]
disabled = false
format = "[$symbol](bg:#a3aed2 fg:#090c0c)($style)"
style = "bg:#a3aed2"

[os.symbols]
Alpaquita = " " # nf-fa-bell
Alpine = " " # nf-linux-alpine
Amazon = " " # nf-fa-amazon
Android = " " # nf-dev-android
Arch = " " # nf-linux-archlinux
Artix = " " # nf-linux-artix
CentOS = " " # nf-linux-centos
Debian = " " # nf-linux-debian
DragonFly = " " # nf-fae-butterfly
Emscripten = " " # nf-fa-toggle_on
EndeavourOS = " " # nf-linux-endeavour
Fedora = " " # nf-linux-fedora
FreeBSD = " " # nf-linux-freebsd
Garuda = "󰛓 " # nf-md-feather
Gentoo = " " # nf-linux-gentoo
HardenedBSD = "󰔇  " # nf-md-tennis_ball
Illumos = " " # nf-linux-illumos
Linux = " " # nf-linux-tux
Mabox = "󰆦  " # nf-fa-cube
Macos = " " # nf-linux-apple
Manjaro = " " # nf-linux-manjaro
Mariner = " " # nf-fa-life_saver
MidnightBSD = " " # nf-fa-moon_o
Mint = "󰣭  " # nf-md-linux_mint
NetBSD = " " # nf-fa-flag
NixOS = " " # nf-linux-nixos
OpenBSD = " " # nf-linux-openbsd
OpenCloudOS = " " # nf-fa-cloud
openEuler = "󰏒  " # nf-md-owl
openSUSE = " " # nf-linux-opensuse
OracleLinux = "󰌷  " # nf-md-link
Pop = " " # nf-linux-pop_os
Raspbian = " " # nf-linux-raspberry_pi
Redhat = "󱄛 " # nf-md-redhat
RedHatEnterprise = " " # nf-linux-redhat
Redox = "󰀘  " # nf-md-orbit
Solus = " " # nf-linux-solus
SUSE = " " # nf-linux-opensuse
Ubuntu = " " # nf-linux-ubuntu
Unknown = " " # nf-fa-question_circle
Windows = " " # nf-fa-windows
